package com.star.foodfans.entity;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

@Entity
public class Achievemenkindtinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievemenkindtinfo.typeid
     *
     * @mbggenerated
     */
    @PrimaryKey
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievemenkindtinfo.meaning
     *
     * @mbggenerated
     */
    private String meaning;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column achievemenkindtinfo.privileges
     *
     * @mbggenerated
     */
    private String privileges;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievemenkindtinfo.typeid
     *
     * @return the value of achievemenkindtinfo.typeid
     *
     * @mbggenerated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievemenkindtinfo.typeid
     *
     * @param typeid the value for achievemenkindtinfo.typeid
     *
     * @mbggenerated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievemenkindtinfo.meaning
     *
     * @return the value of achievemenkindtinfo.meaning
     *
     * @mbggenerated
     */
    public String getMeaning() {
        return meaning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievemenkindtinfo.meaning
     *
     * @param meaning the value for achievemenkindtinfo.meaning
     *
     * @mbggenerated
     */
    public void setMeaning(String meaning) {
        this.meaning = meaning == null ? null : meaning.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column achievemenkindtinfo.privileges
     *
     * @return the value of achievemenkindtinfo.privileges
     *
     * @mbggenerated
     */
    public String getPrivileges() {
        return privileges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column achievemenkindtinfo.privileges
     *
     * @param privileges the value for achievemenkindtinfo.privileges
     *
     * @mbggenerated
     */
    public void setPrivileges(String privileges) {
        this.privileges = privileges == null ? null : privileges.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", typeid=").append(typeid);
        sb.append(", meaning=").append(meaning);
        sb.append(", privileges=").append(privileges);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}