package com.star.foodfans.entity;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

@Entity
public class Articleinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.articleId
     *
     * @mbggenerated
     */
    @PrimaryKey
    private Integer articleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.urls
     *
     * @mbggenerated
     */
    private String urls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.praiseNum
     *
     * @mbggenerated
     */
    private Integer praisenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.readNum
     *
     * @mbggenerated
     */
    private Integer readnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.commentNum
     *
     * @mbggenerated
     */
    private Integer commentnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.avgscore
     *
     * @mbggenerated
     */
    private float avgscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.creatStamp
     *
     * @mbggenerated
     */
    private Long creatstamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.isTop
     *
     * @mbggenerated
     */
    private Integer istop;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.visitNum
     *
     * @mbggenerated
     */
    private Integer visitnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.tag
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column articleinfo.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table articleinfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.articleId
     *
     * @return the value of articleinfo.articleId
     *
     * @mbggenerated
     */
    public Integer getArticleid() {
        return articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.articleId
     *
     * @param articleid the value for articleinfo.articleId
     *
     * @mbggenerated
     */
    public void setArticleid(Integer articleid) {
        this.articleid = articleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.userId
     *
     * @return the value of articleinfo.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.userId
     *
     * @param userid the value for articleinfo.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.title
     *
     * @return the value of articleinfo.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.title
     *
     * @param title the value for articleinfo.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.urls
     *
     * @return the value of articleinfo.urls
     *
     * @mbggenerated
     */
    public String getUrls() {
        return urls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.urls
     *
     * @param urls the value for articleinfo.urls
     *
     * @mbggenerated
     */
    public void setUrls(String urls) {
        this.urls = urls == null ? null : urls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.praiseNum
     *
     * @return the value of articleinfo.praiseNum
     *
     * @mbggenerated
     */
    public Integer getPraisenum() {
        return praisenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.praiseNum
     *
     * @param praisenum the value for articleinfo.praiseNum
     *
     * @mbggenerated
     */
    public void setPraisenum(Integer praisenum) {
        this.praisenum = praisenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.readNum
     *
     * @return the value of articleinfo.readNum
     *
     * @mbggenerated
     */
    public Integer getReadnum() {
        return readnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.readNum
     *
     * @param readnum the value for articleinfo.readNum
     *
     * @mbggenerated
     */
    public void setReadnum(Integer readnum) {
        this.readnum = readnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.commentNum
     *
     * @return the value of articleinfo.commentNum
     *
     * @mbggenerated
     */
    public Integer getCommentnum() {
        return commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.commentNum
     *
     * @param commentnum the value for articleinfo.commentNum
     *
     * @mbggenerated
     */
    public void setCommentnum(Integer commentnum) {
        this.commentnum = commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.avgscore
     *
     * @return the value of articleinfo.avgscore
     *
     * @mbggenerated
     */
    public float getAvgscore() {
        return avgscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.avgscore
     *
     * @param avgscore the value for articleinfo.avgscore
     *
     * @mbggenerated
     */
    public void setAvgscore(float avgscore) {
        this.avgscore = avgscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.creatStamp
     *
     * @return the value of articleinfo.creatStamp
     *
     * @mbggenerated
     */
    public Long getCreatstamp() {
        return creatstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.creatStamp
     *
     * @param creatstamp the value for articleinfo.creatStamp
     *
     * @mbggenerated
     */
    public void setCreatstamp(Long creatstamp) {
        this.creatstamp = creatstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.isTop
     *
     * @return the value of articleinfo.isTop
     *
     * @mbggenerated
     */
    public Integer getIstop() {
        return istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.isTop
     *
     * @param istop the value for articleinfo.isTop
     *
     * @mbggenerated
     */
    public void setIstop(Integer istop) {
        this.istop = istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.visitNum
     *
     * @return the value of articleinfo.visitNum
     *
     * @mbggenerated
     */
    public Integer getVisitnum() {
        return visitnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.visitNum
     *
     * @param visitnum the value for articleinfo.visitNum
     *
     * @mbggenerated
     */
    public void setVisitnum(Integer visitnum) {
        this.visitnum = visitnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.tag
     *
     * @return the value of articleinfo.tag
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.tag
     *
     * @param tag the value for articleinfo.tag
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column articleinfo.content
     *
     * @return the value of articleinfo.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column articleinfo.content
     *
     * @param content the value for articleinfo.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table articleinfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", articleid=").append(articleid);
        sb.append(", userid=").append(userid);
        sb.append(", title=").append(title);
        sb.append(", urls=").append(urls);
        sb.append(", praisenum=").append(praisenum);
        sb.append(", readnum=").append(readnum);
        sb.append(", commentnum=").append(commentnum);
        sb.append(", avgscore=").append(avgscore);
        sb.append(", creatstamp=").append(creatstamp);
        sb.append(", istop=").append(istop);
        sb.append(", visitnum=").append(visitnum);
        sb.append(", tag=").append(tag);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}