package com.star.foodfans.entity;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

@Entity
public class Commentinfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo.commentId
     *
     * @mbggenerated
     */
    @PrimaryKey
    private Integer commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo.contentId
     *
     * @mbggenerated
     */
    private String contentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo.creatStamp
     *
     * @mbggenerated
     */
    private Long creatstamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commentinfo.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo.commentId
     *
     * @return the value of commentinfo.commentId
     *
     * @mbggenerated
     */
    public Integer getCommentid() {
        return commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo.commentId
     *
     * @param commentid the value for commentinfo.commentId
     *
     * @mbggenerated
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo.userId
     *
     * @return the value of commentinfo.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo.userId
     *
     * @param userid the value for commentinfo.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo.contentId
     *
     * @return the value of commentinfo.contentId
     *
     * @mbggenerated
     */
    public String getContentid() {
        return contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo.contentId
     *
     * @param contentid the value for commentinfo.contentId
     *
     * @mbggenerated
     */
    public void setContentid(String contentid) {
        this.contentid = contentid == null ? null : contentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo.url
     *
     * @return the value of commentinfo.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo.url
     *
     * @param url the value for commentinfo.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo.score
     *
     * @return the value of commentinfo.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo.score
     *
     * @param score the value for commentinfo.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo.creatStamp
     *
     * @return the value of commentinfo.creatStamp
     *
     * @mbggenerated
     */
    public Long getCreatstamp() {
        return creatstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo.creatStamp
     *
     * @param creatstamp the value for commentinfo.creatStamp
     *
     * @mbggenerated
     */
    public void setCreatstamp(Long creatstamp) {
        this.creatstamp = creatstamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo.status
     *
     * @return the value of commentinfo.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo.status
     *
     * @param status the value for commentinfo.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commentinfo.content
     *
     * @return the value of commentinfo.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commentinfo.content
     *
     * @param content the value for commentinfo.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commentinfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentid=").append(commentid);
        sb.append(", userid=").append(userid);
        sb.append(", contentid=").append(contentid);
        sb.append(", url=").append(url);
        sb.append(", score=").append(score);
        sb.append(", creatstamp=").append(creatstamp);
        sb.append(", status=").append(status);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}