package com.star.foodfans.entity;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.io.Serializable;

@Entity
public class Reward implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.rewardId
     *
     * @mbggenerated
     */
    @PrimaryKey
    private Integer rewardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.sender
     *
     * @mbggenerated
     */
    private Integer sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.receiver
     *
     * @mbggenerated
     */
    private Integer receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.size
     *
     * @mbggenerated
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.timestamp
     *
     * @mbggenerated
     */
    private Long timestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reward.describe
     *
     * @mbggenerated
     */
    private String describe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reward
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.rewardId
     *
     * @return the value of reward.rewardId
     *
     * @mbggenerated
     */
    public Integer getRewardid() {
        return rewardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.rewardId
     *
     * @param rewardid the value for reward.rewardId
     *
     * @mbggenerated
     */
    public void setRewardid(Integer rewardid) {
        this.rewardid = rewardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.sender
     *
     * @return the value of reward.sender
     *
     * @mbggenerated
     */
    public Integer getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.sender
     *
     * @param sender the value for reward.sender
     *
     * @mbggenerated
     */
    public void setSender(Integer sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.receiver
     *
     * @return the value of reward.receiver
     *
     * @mbggenerated
     */
    public Integer getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.receiver
     *
     * @param receiver the value for reward.receiver
     *
     * @mbggenerated
     */
    public void setReceiver(Integer receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.size
     *
     * @return the value of reward.size
     *
     * @mbggenerated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.size
     *
     * @param size the value for reward.size
     *
     * @mbggenerated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.timestamp
     *
     * @return the value of reward.timestamp
     *
     * @mbggenerated
     */
    public Long getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.timestamp
     *
     * @param timestamp the value for reward.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reward.describe
     *
     * @return the value of reward.describe
     *
     * @mbggenerated
     */
    public String getDescribe() {
        return describe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reward.describe
     *
     * @param describe the value for reward.describe
     *
     * @mbggenerated
     */
    public void setDescribe(String describe) {
        this.describe = describe == null ? null : describe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rewardid=").append(rewardid);
        sb.append(", sender=").append(sender);
        sb.append(", receiver=").append(receiver);
        sb.append(", size=").append(size);
        sb.append(", timestamp=").append(timestamp);
        sb.append(", describe=").append(describe);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}