package com.star.foodfans.dao;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.OnConflictStrategy;
import androidx.room.Query;
import androidx.room.Update;

import com.star.foodfans.entity.Achievemenkindtinfo;

import java.util.List;

@Dao
public interface AchievemenkindtinfoDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    @Query("DELETE FROM Achievemenkindtinfo WHERE typeid = :typeid")
    int deleteAchievementkindinfo(Integer typeid);

    @Query("DELETE FROM Achievemenkindtinfo")
    int deleteAllAchievemenkindtinfo();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    void insertAchievemenkindtinfo(Achievemenkindtinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Achievemenkindtinfo WHERE typeid = :typeid")
    LiveData<Achievemenkindtinfo> selectAchievemenkindtinfo(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Achievemenkindtinfo")
    LiveData<List<Achievemenkindtinfo>> selectAllAchievemenkindtinfo();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table achievemenkindtinfo
     *
     * @mbggenerated
     */
    @Update
    int updateAchievemenkindtinfo(Achievemenkindtinfo record);

}