package com.star.foodfans.dao;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import com.star.foodfans.entity.Friendrange;
import java.util.List;

@Dao
public interface FriendrangeDao {

    @Query("DELETE FROM Friendrange")
    int deleteAllFriendrange();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    @Query("DELETE FROM Friendrange WHERE userid = :userid and friendid = :friendid")
    int deleteFriendrange(Integer userid, Integer friendid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    @Insert
    void insert(Friendrange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Friendrange WHERE userid = :userid and friendid = :friendid")
    LiveData<Friendrange> selectFriendrange(Integer userid, Integer friendid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Friendrange")
    LiveData<List<Friendrange>> selectAllFriendrange();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrange
     *
     * @mbggenerated
     */@Update
    int updateFriendrange(Friendrange record);

    @Query("SELECT * FROM Friendrange WHERE userid = :userid")
    LiveData<List<Friendrange>> selectPersonalFriends(Integer userid);

}