package com.star.foodfans.dao;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import com.star.foodfans.entity.Goods;

import java.util.List;

@Dao
public interface GoodsDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    @Query("DELETE FROM Goods WHERE id = :id")
    int deleteGoods(Integer id);

    @Query("DELETE FROM Goods")
    int deleteAllGoods();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    @Insert
    void insertGoods(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Goods WHERE id = :id")
    LiveData<Goods> selectGoods(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Goods")
    LiveData<List<Goods>> selectAllGoods();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    @Update
    int updateGoods(Goods record);


}