package com.star.foodfans.dao;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import com.star.foodfans.entity.Message;

import java.util.List;

@Dao
public interface MessageDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    @Query("DELETE FROM Message WHERE msgid = :msgid")
    int deleteMessage(Integer msgid);

    @Query("DELETE FROM Message")
    int deleteAllMessage();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    @Insert
    void insertMessage(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Message WHERE msgid = :msgid")
    LiveData<Message> selectMessage(Integer msgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Message")
    LiveData<List<Message>> selectAllMessage();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    @Update
    int updateMessage(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Message WHERE receive = :uid")
    LiveData<List<Message>> selectOnesMessage(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated
     */
    @Query("UPDATE Message SET isread = 1 WHERE receive = :uid")
    void readMessage(Integer uid);

}