package com.star.foodfans.dao;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import com.star.foodfans.entity.Record;

import java.util.List;

@Dao
public interface RecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated
     */
    @Query("DELETE FROM Record WHERE id = :id")
    int deleteRecord(Integer id);

    @Query("DELETE FROM Record")
    int deleteAllRecord();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated
     */
    @Insert
    void insertRecord(Record record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Record WHERE id = :id")
    LiveData<Record> selectRecord(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Record")
    LiveData<List<Record>> selectAllRecord();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table record
     *
     * @mbggenerated
     */
    @Update
    int updateRecord(Record record);

    @Query("SELECT * FROM Record WHERE userid = :id")
    LiveData<List<Record>> selectRecordByUserId(int id);

}