package com.star.foodfans.dao;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;

import com.star.foodfans.entity.Reward;

import java.util.List;

@Dao
public interface RewardDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    @Query("DELETE FROM Reward WHERE rewardid = :rewardid")
    int deleteReward(Integer rewardid);

    @Query("DELETE FROM Reward")
    int deleteAllReward();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    @Insert
    void insertReward(Reward record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Reward WHERE rewardid = :rewardid")
    LiveData<Reward> selectReward(Integer rewardid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    @Query("SELECT * FROM Reward")
    LiveData<List<Reward>> selectAllReward();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reward
     *
     * @mbggenerated
     */
    @Update
    int updateReward(Reward record);
}